version: '2'

services:

  mongodb:
    image: need-help-mongodb-dev:latest
    ports:
      - 27017:27017
    volumes:
      - ./db_data_dev:/data/db
    environment:
      - MONGODB_ADMIN_USER
      - MONGODB_ADMIN_PASS
      - MONGODB_APPLICATION_DATABASE
      - MONGODB_APPLICATION_USER
      - MONGODB_APPLICATION_PASS
