version: '2'

services:
  need-help:
    image:  need-help:latest
    ports:
      - 80:3000
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_APPLICATION_DATABASE
      - MONGODB_APPLICATION_USER
      - MONGODB_APPLICATION_PASS
    depends_on:
      - mongodb

  mongodb:
    image: need-help-mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - ./db_data:/data/db
    environment:
      - MONGODB_ADMIN_USER
      - MONGODB_ADMIN_PASS
      - MONGODB_APPLICATION_DATABASE
      - MONGODB_APPLICATION_USER
      - MONGODB_APPLICATION_PASS
